### ISSUE TITLE
client_oid

### ISSUE THREAD

**Issue by franklin770** [dougdellolio/gdax-csharp#102]
Hi
I'm trying to submit an order using your OrdersService.cs. 
I modified the func to accept  the "client_oid"

To create this I am using c# guid type
Guid client_oid = Guid.NewGuid();

The issue is that the id that is returned is not the same as the client_oid that I sent and therefore, I can’t identify the trade.

I am using the sandbox and am not using the websocket feed.

so,
Is this a sandbox issue?
Is my guid invalid since it is GUID and technically not UUID?
Is it because I need to specifically use websockets to get the client_oid ( and what I am seeing is the gdax order_id?)

Any help would be appreciated

Thanks
Franklin

p.s. great code

**Comment by Sotam** [comment]
I assume the `client_oid` isn't retrieved correct by this library. I have almost a PR ready for this one (coding done, need to do the testing). I think there should be a `client_oid` property in `OrderResponse.cs`, not completely sure tho.

**Comment by chrisw000** [comment]
When you place or get an order it seems there is no client_oid on the response json

I'd assumed that if you want to use client_oid - you need to manage that side of it youself? 

The docs talk about client_oid being seen in the websocket received feed before the order_id comes back from the original place request - so users of websocket should use received to pair up order_id and client_oid?

And if you're using the rest side of it - you'd pair up the order_id from the place order response?

**Comment by franklin770** [comment]
Hi.
The doc mentions websocket, but it is vague. Someone on the gdax gethub said that it is ONLY on the websocket feed, so I guess I need to implement that.

Also, I  am not even sure that the sandbox has a web feed. If they do, I do not know the channel.  Please let me know what it is, if you know, since I cannot find it.

My other concern was the GUID vs the UUID.  It should be the same but I do not know for sure.

I also do not know how gdax handles fills. Is everything under the gdax orderid or are there different id's for each fill?

At this point I need to start using the real Gdax to figure this stuff out.

Thanks for the response

**Comment by Sotam** [comment]
The sandbox has a webfeed, the channels are the same. Just change the url, and you are good to go (however, sandbox is not 100% a clone of the real GDAX)
