### ISSUE TITLE
ProductService.GetHistoricRatesAsync throws InvalidOperationException when no candles

### ISSUE THREAD

**Issue by luckicongee** [dougdellolio/gdax-csharp#103]
The method `ProductService.GetHistoricRatesAsync` will throw `InvalidOperationException` when there is no candle returned from GDAX API. The cause is in the line below:

```
batchEnd = candleList.Last()?.Time;
```

The `Last` method throws `InvalidOperationException` when the list is empty. It should use `LastOrDefault`.

**Comment by chrisw000** [comment]
You are quite right.... I'll do a PR

**Comment by dougdellolio** [comment]
thanks @chrisw000. fix has been merged and will go out with next release
