### ISSUE TITLE
Issue with placing orders hanging/no response?

### ISSUE THREAD

**Issue by BradForsythe** [dougdellolio/gdax-csharp#110]
I am sure I must be doing something wrong, anyone with helpful advice would be great...
I made a simple Winform with a button to enter an order.   When the method reaches execution reaches abstractservices ... we hang / lock up at  var httpResponseMessage = await httpClient.SendASync(httpRequestMessage).ConfigureAwait(false);

I am able to make non-account calls.  I was thinking maybe the api key I have is not correct, but I would expect a response instead of a lock up.   Here is the simple mainform code with the keys removed:

public OrdersService ordersService;
public ProductsService productService;
    
public Form1()
        {
            InitializeComponent();
  //  GDAX HTTP client services (for order entry and status)
            bool sandBox = true;
            var clock = new Clock();
            var httpRequestMessageService = new HttpRequestMessageService(clock, sandBox);
            var httpClient = new HttpClient();
            var queryBuilder = new QueryBuilder();
            var authenticator = new Authenticator(  "apikey", "secret==", "passphrase");
            ordersService = new OrdersService(httpClient, httpRequestMessageService, authenticator);
            productService = new ProductsService(httpClient, httpRequestMessageService, authenticator, queryBuilder);
            
        }

        private void button1_Click(object sender, EventArgs e)
        {
            var reponse = ordersService.PlaceLimitOrderAsync(OrderSide.Buy, ProductType.BtcUsd, .1M, 5000.0M);

          }

Thanks anyone for advice.

**Comment by dougdellolio** [comment]
@BradForsythe it looks like the initialization of the client isn't correct.

try doing this. you don't need to initialize a client or query builder because it is all done for you:

````
//create an authenticator with your apiKey, apiSecret and passphrase
var authenticator = new Authenticator("<apiKey>", "<apiSecret>", "<passphrase>");

//create the GDAX client and set true for sandbox
var gdaxClient = new GDAXSharp.GDAXClient(authenticator, true);

//call the place limit order on button click from the client
    private void button1_Click(object sender, EventArgs e)
    {
        var reponse = gdaxClient.OrdersService.PlaceLimitOrderAsync(OrderSide.Buy, ProductType.BtcUsd, .1M, 5000.0M);
    }

let me know if you are still having problems

**Comment by BradForsythe** [comment]
Thanks Doug for your quick response, your help is super appreciated!!   I've done the following and the response from the task is "waiting for activation" which I think is saying the task is not completing...

I've tried also to do OrderResponse respoone = ......().Result and I get the "lockup" condition.

Interestingly the other way I did it...(the wrong way) I was able to get products successfully.  Now I get the same result from both methods (tasks).

Thanks again!!!!!!!!!!!!!



public partial class Form1 : Form
    {
        static Authenticator authenticator = new Authenticator("aaaaaa",  "bbbbb", "cccccr");

        //create the GDAX client and set true for sandbox
        static GDAXClient.GDAXClient gdaxClient = new GDAXClient.GDAXClient(authenticator, true);
      
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            var reponse1 = gdaxClient.OrdersService.PlaceLimitOrderAsync(OrderSide.Buy, ProductType.BtcUsd, .1M, 5000.0M);
            
            var response2 = gdaxClient.ProductsService.GetAllProductsAsync();
            
        }
    }

**Comment by dougdellolio** [comment]
@BradForsythe  no worries

you may have to mark the `button1_Click` as async and use await for the response

`var response1 = await gdaxClient.OrdersService.PlaceLimitOrderAsync(OrderSide.Buy, ProductType.BtcUsd, .1M, 5000.0M);`

and youre saying calling `.Result` after place order work?

**Comment by BradForsythe** [comment]
EDIT - 

I am making progress!   
Changed button1_Click to async and applied await to the services methods (Tasks).
I am able to get the products successfully and the orders I get invalid API key which may be highly likely.


private async void button1_Click(object sender, EventArgs e)
{
            var reponse1 = await gdaxClient.OrdersService.PlaceLimitOrderAsync(OrderSide.Buy, ProductType.BtcUsd, .1M, 5000.0M);         
            var response2 = await gdaxClient.ProductsService.GetAllProductsAsync();
}

**Comment by dougdellolio** [comment]
@BradForsythe great! also make sure that you give the API key permission to Trade as well when you generate the key.

**Comment by BradForsythe** [comment]
Doug closing this "issue" .... user error.  Thanks for your help.   Not hanging now and the rest is probably solvable.
