### ISSUE TITLE
nulls in Gdax ticker

### ISSUE THREAD

**Issue by franklin770** [dougdellolio/gdax-csharp#111]
"best_bid" is **null**,
  NullValueHandling = **NullValueHandling.Ignore,**

Exception thrown: 'System.DivideByZeroException' in mscorlib.dll
Ticker-{"type":"ticker","product_id":"BCH-BTC","price":0,"open_24h":0,"volume_24h":0,"low_24h":0,"high_24h":0,"volume_30d":"289.89382751","best_bid":**null**,"best_ask":"10.98"}
Subscriptions-{"type":"subscriptions","channels":[{"name":"user","product_ids":["BTC-USD","BTC-EUR","BTC-GBP","ETH-USD","ETH-EUR","ETH-BTC","LTC-USD","LTC-EUR","LTC-BTC","BCH-USD","BCH-EUR","BCH-BTC"]},{"name":"ticker","product_ids":["BTC-USD","BTC-EUR","BTC-GBP","ETH-USD","ETH-EUR","ETH-BTC","LTC-USD","LTC-EUR","LTC-BTC","BCH-USD","BCH-EUR","BCH-BTC"]}]}
         
private static JsonSerializerSettings SerializerSettings { get; } = new JsonSerializerSettings
        {
            FloatParseHandling = FloatParseHandling.Decimal,
            NullValueHandling = **NullValueHandling.Ignore,**
            ContractResolver = new DefaultContractResolver
            {
                NamingStrategy = new SnakeCaseNamingStrategy()
            }
        };

**Comment by franklin770** [comment]
Hi Doug

It is on the ticker channel.
there is definitely an exception being thrown

You have NullValueHandling.Ignore set,   so it  is being ignored

if you add Error = HandleDeserializationError   you will catch it.

private static JsonSerializerSettings SerializerSettings { get; } = new
JsonSerializerSettings
        {
            FloatParseHandling = FloatParseHandling.Decimal,
            NullValueHandling = NullValueHandling.Ignore,
            ContractResolver = new DefaultContractResolver
            {
                NamingStrategy = new SnakeCaseNamingStrategy()
            },
            Error = HandleDeserializationError
        };

 public static void HandleDeserializationError(object sender,
ErrorEventArgs errorArgs)
        {
            //    errorArgs.ErrorContext.Handled = true;
            //}

        }


However, looking into it more, there may be another error on my side.
investigating.

BTW

I am getting this quite often.


        private void WebSocket_Error(object sender,
SuperSocket.ClientEngine.ErrorEventArgs e)
        {
            throw new GDAXSharpWebSocketException($"WebSocket Feed Error:
{e.Exception.Message}")
            {
                WebSocket = WebSocketFeed,
                StatusCode = WebSocketFeed.State,
                ErrorEvent = e

            };
        }


Thanks

**Comment by franklin770** [comment]
yes I am using user, and ticker channel

**Comment by franklin770** [comment]
Hi Doug.

I am doing math and the  DivideByZeroException that I was getting is also
on  my side.
I mistakenly thought that the   DivideByZeroException that is being thrown
in the websocket was the cause

Thanks for replying

Regards

**Comment by dougdellolio** [comment]
glad its fixed 😄 will close this.

**Comment by franklin770** [comment]
Thx.

That's the problem with using the stupid sandbox. The prices are all off
from the actual production prices, and it returns 0 for bid/ask etc.

I have to move to the realtime but my code is not there yet
