### ISSUE TITLE
[Question] Use UnAuthenticated Websocket feed

### ISSUE THREAD

**Issue by ElanHasson** [dougdellolio/gdax-csharp#119]
How can I access the public web socket feed?

**Comment by dougdellolio** [comment]
it is actually not possible currently as it lives on the GDAXClient. I can add this ability shortly.

**Comment by BradForsythe** [comment]
@dougdellolio  while your at it....do you want to add in the ability to unsubscribe/add subscription/remove subscription while your at it?  or do you want me to do a PR for that feature?   No problem either way... :)

**Comment by ElanHasson** [comment]
Oh yes please do.

**Comment by dougdellolio** [comment]
@BradForsythe that should go in a separate PR. Feel free to take it on if not I can get to it after I add this.

**Comment by BradForsythe** [comment]
@dougdellolio ok cool.   I'll wait for your release.

**Comment by dougdellolio** [comment]
@ElanHasson i have merged this here https://github.com/dougdellolio/gdax-csharp/pull/120. let me know if you have any questions/problems with it. otherwise it will go out with next release. thx!
