### ISSUE TITLE
[BUG] Invalid Stop Limit Exception on Standard Limit and Market Orders

### ISSUE THREAD

**Issue by BradForsythe** [dougdellolio/gdax-csharp#121]
Now when entering Limit or Market Orders are entered, an exception is thrown for "invalid stop price" .   I haven't changed my interface but maybe something else has changed when I moved to the latest merge after the Stop Limit Orders were added.   I'll see what I can troubleshoot, just wondering if anyone else has seen this with market or limit orders on the latest release.

**Comment by BradForsythe** [comment]
Update:  Looks like even for Limit or Market orders Stop Type is being defaulted to "loss" with a stop price of 0.   By GDAX specification the stop price will be used only when stop type is defined.   Hence the exception of invalid stop price of 0.   I need to revert back tonight and dig in a little tomorrow.   I had 175 orders rejected while I was out to dinner!  Probably all bad orders anyway ....   Maybe there is something else going on here, but this is what it looks like now.

**Comment by dougdellolio** [comment]
@BradForsythe apologies. i should be more careful when reviewing additions to Order service. i am reverting that PR for now until I can get a fix in

**Comment by dougdellolio** [comment]
Reverted the change and released in v1.0.17. Will be able to add it back properly tonight. 😞

**Comment by BradForsythe** [comment]
@dougdellolio no worries, it was a quick find.

**Comment by BradForsythe** [comment]
Something interesting did come out of this.   When an order is entered GDAX usually responds  *politely* with a "rejected" status and a reason,   Such as "post only", or "service not available".   But when an invalid stop price is encountered an exception is caught in  SendHttpRequestMessageAsync and thrown.   Might be nice to handle the exception at the SendServiceCall and return an appropriate status so we don't have to catch this exception when entering orders.  Just thinking out loud on this.

**Comment by BradForsythe** [comment]
@dougdellolio reverted back, issue is solved.
