### ISSUE TITLE
Support the ability to specify "funds" field when placing market orders

### ISSUE THREAD

**Issue by abharath27** [dougdellolio/gdax-csharp#124]
PlaceMarketOrderAsync currently doesn't support the ability to specify the amount of USD you want to use to buy crypto. I was planning on writing an app that places a market order every week using a fixed USD amount (A). 
As a workaround, I'm getting the ticker price (P) of crypto  and placing an order of size A/P.

**Comment by dougdellolio** [comment]
@abharath27 thanks for the request. i have added this here: https://github.com/dougdellolio/gdax-csharp/pull/125. Let me know if you see any problem with it otherwise I will merge and push with next release.
