### ISSUE TITLE
Get trades stream from Web Socket.

### ISSUE THREAD

**Issue by aspramsh** [dougdellolio/gdax-csharp#142]
HI @dougdellolio . I need to get trades stream from websocket. Is there some function for this? I have noticed GetTradesAsync(), but it works with API.

**Comment by dougdellolio** [comment]
hi @aspramsh. If you are looking to see the latest trades I would recommend subscribing to the `Ticker` channel on the Websocket. you can view some code examples here: https://github.com/dougdellolio/gdax-csharp/issues/118

**Comment by aspramsh** [comment]
Ok @dougdellolio. Thanks a lot 👍
