### ISSUE TITLE
Why only specific values for ProductType enum?

### ISSUE THREAD

**Issue by aspramsh** [dougdellolio/gdax-csharp#143]
@dougdellolio Hi. I would like to know if Gdax websocket supports other pairs (the http api gives 203 pairs) than you provided in ProductType enum?

**Comment by dougdellolio** [comment]
The pairs provided in ProductType are the ones provided by the `/products` endpoint which are the only currency pairs available for trading (12 of them). Is there a list from the documentation that you can provide? I can't seem to find it

**Comment by aspramsh** [comment]
That is correct, thanks a lot and sorry for the mess.
