### ISSUE TITLE
Getting bad request everytime

### ISSUE THREAD

**Issue by axeldomingues** [dougdellolio/gdax-csharp#15]
While using this API Client i am getting bad requests everytime from GDax  Sandbox API. Any idea?

Note: Using your sandbox example.

**Comment by dougdellolio** [comment]
@axeldomingues you must create a separate sandbox account from your regular account here: https://public.sandbox.gdax.com/ and then generate your API keys from here https://public.sandbox.gdax.com/settings/api giving it all necessary permissions. 

when you have that then you can use any of the services (examples in readme). If you are trying to place an order make sure there are sufficient funds in the sandbox account to do so.

if this still doesn't work please provide which service you are trying to use.

also - better error handling is to come.

**Comment by axeldomingues** [comment]
Thank you so much! Indeed that was the problem! Closing it!
