### ISSUE TITLE
BookRequest Issue

### ISSUE THREAD

**Issue by combinu** [dougdellolio/gdax-csharp#16]
Hi when i try to get a book request as follows:

 GDAXClient.Services.Products.Models.Responses.ProductsOrderBookResponse book = await gClient.ProductsService.GetProductOrderBookAsync(GetProductType(product));

I get only 1 bid, asks is null and the sequence number. Is there something wrong?

**Comment by dougdellolio** [comment]
@combinu Sounds like this is related to https://github.com/dougdellolio/gdax-csharp/pull/13. If there is no response from @JamesTFreelance shortly I will open up another PR to fix this issue

**Comment by dougdellolio** [comment]
closing this issue as it is now fixed with v1.0.4
