### ISSUE TITLE
Limit Order Bad request due to content format

### ISSUE THREAD

**Issue by rr404** [dougdellolio/gdax-csharp#23]
Hi,
I got a badrequest when callling OrderService.PlaceLimitOrderAsync(...)

It sems that when you serialize your new Order the price ans size are still floats when they should be converted to string.

At the momment you're sending an order of that format : 
{
    "size": 0.01,
    "price": 0.100,
    "side": "buy",
    "product_id": "BTC-USD"
}

_It returns a bad request_

When i tried to force full strings (for price and size) it works
{
    "size": "0.01",
    "price": "0.100",
    "side": "buy",
    "product_id": "BTC-USD"
}

For now I'm doing an ugly tweak : 
var newOrder = JsonConvert.SerializeObject(new Dictionary<string, string>
            {
                {"side",side.ToString().ToLower()},
                {"product_id",productId.ToDasherizedUpper()},
                {"type",OrderType.Limit.ToString().ToLower()},
                {"price",""+price},
                {"size",""+size}
            });

But I think it can be nicer to have the serialization or conversion directly within the Model.

BTW thanks for this really cool Gdax client.

**Comment by dougdellolio** [comment]
@rr404 thanks for the feedback!

can you provide to me an example of a call that you are making with the service where you are seeing a bad request? I can't seem to reproduce this locally 😕 

here is how it can be used: `gdaxClient.OrdersService.PlaceLimitOrderAsync(OrderSide.Buy, ProductType.BtcUsd, 0.01M, 0.01M)`

would love this fix this ASAP if it is indeed an issue.

**Comment by rr404** [comment]
Ok I'll work on a short piece of code to test it and will submit it.
Meanwhile i'm opening an other issue that may be remotely linked

**Comment by rr404** [comment]
My bad, I misinterpreted the error message, did not look deep enough in the code at the time, sorry for the bother.
The initial code works
