### ISSUE TITLE
Trying to use sandbox but insufficient funds

### ISSUE THREAD

**Issue by bdelaney** [dougdellolio/gdax-csharp#24]
Any idea on how I add funds in my sandbox. GDAX is brand new to me, and I have not set up any real fund accounts. Not obvious in Sandbox how I do this.

**Comment by axeldomingues** [comment]
You can go to trading view in the public sandbox api and deposit fake funds from fake accounts.

https://public.sandbox.gdax.com/trade/BTC-USD

**Comment by bdelaney** [comment]
That was easy once I found the right account to deposit from. Thanks!
