### ISSUE TITLE
Bad timestamp format due to different culture info

### ISSUE THREAD

**Issue by rr404** [dougdellolio/gdax-csharp#26]
Hi,

Some friends got an issue the timestamp format
On their computer it returns a number with a comma instead of a dot due to their computer's culture info (fr-FR).

It's fixable by doing a quick conversion in the HttpMessageService.cs  (or in the DateExtensions it self as a string GetUniversalTimestampString() Methode

`var ci = new System.Globalization.CultureInfo("en-US");
DateTime.UtcNow.ToTimeStamp().toString(ci)`

_ps: Checking if that's what caused the other issue  about creating an order but I think not as I experience_

**Comment by dougdellolio** [comment]
@rr404 i have a fix and merged this here which will go out in next release: https://github.com/dougdellolio/gdax-csharp/pull/27. let me know if you still are seeing a problem.

thanks so much!
