### ISSUE TITLE
GetAllAccountsAsync is nto working

### ISSUE THREAD

**Issue by moski0** [dougdellolio/gdax-csharp#31]
Hi..

I would like to use your API...

but your testing example is not working...

what are you usign as signature ?

could you check it your example is working ? 

please see me test code bellow...

Many thanks
Tomas

-------------------------------------------------------

using GDAXClient.Authentication;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace test
{
    class Program
    {
        static string apiSecret = "xxx";

        private static async void xxx()
        {
            string phrase = "xxx";
            string apiKey = "xxx";

            string signature = "";

            string ts = GetNonce();
            string method = "/accounts";
            string sig = GetSignature(ts, "GET", method, string.Empty);

            signature = sig;

            GDAXClient.Authentication.Authenticator aut = new GDAXClient.Authentication.Authenticator(apiKey, signature, phrase);
            GDAXClient.GDAXClient client = new GDAXClient.GDAXClient(aut);
            var a = await client.AccountsService.GetAllAccountsAsync();

        }

        static void Main(string[] args)
        {
            xxx();

        }

        private static string GetNonce()
        {
            String a = (DateTime.Now.ToFileTimeUtc() / 1000).ToString();
            String b = (DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds.ToString();
            return b;
        }

        private static string GetSignature(string nonce, string method, string url, string body)
        {
            string message = string.Concat(nonce, method.ToUpper(), url, body);
            var encoding = new ASCIIEncoding();
            byte[] keyByte = Convert.FromBase64String(apiSecret);
            byte[] messageBytes = encoding.GetBytes(message);
            using (var hmacsha256 = new HMACSHA256(keyByte))
            {
                byte[] hashmessage = hmacsha256.ComputeHash(messageBytes);
                return Convert.ToBase64String(hashmessage);
            }
        }

    }
}

-------------------------------------------------------

**Comment by dougdellolio** [comment]
@moski0 its even easier than that. the client will do all of the signing for you, all you need to do is just pass in your api key, signature (unsigned), and passphrase

so from your example.... it is just this:

````
        GDAXClient.Authentication.Authenticator aut = new GDAXClient.Authentication.Authenticator(<your-apiKey>, <your-unsignedsignature>, <your-phrase>);
        GDAXClient.GDAXClient client = new GDAXClient.GDAXClient(aut);
        var a = await client.AccountsService.GetAllAccountsAsync();
````

let me know if something still doesnt work 😄

**Comment by moski0** [comment]
I have still exception during running GetAllAccountsAsync...

"invalid timestamp"


![x](https://user-images.githubusercontent.com/34658970/34196873-41679dc2-e564-11e7-83c4-55f971552173.png)

**Comment by dougdellolio** [comment]
May be related to https://github.com/dougdellolio/gdax-csharp/issues/26. The issue should have been fixed with v1.0.5 (from this pr https://github.com/dougdellolio/gdax-csharp/pull/27). Make sure you have the latest version from Nuget. If it still doesn't work then it may still be a bug that I will fix.

Let me know!

**Comment by moski0** [comment]
Hi..

yes I have last version 1.0.5 .. (I just tried remoev adn download it again) .. and problem is still the same...

![x](https://user-images.githubusercontent.com/34658970/34207692-d19ab826-e58b-11e7-8cd2-
974fe82e63f2.png)

**Comment by moski0** [comment]
here is me version...

![x](https://user-images.githubusercontent.com/34658970/34207758-1b123614-e58c-11e7-80ed-976302a59f02.png)

**Comment by moski0** [comment]
I checked your fix.. for  #26 .. it does not seems to be related .... ( dot is instead of comma)

see debug..

![x](https://user-images.githubusercontent.com/34658970/34208670-9c3a0b60-e58f-11e7-8194-c7d369adb2da.png)

**Comment by dougdellolio** [comment]
Another user that opened the issue I mentioned above had another fix that seemed to work for him if you would like to try that out. I will be able to make the change tonight.

**Comment by moski0** [comment]
I found it.. now it works .. :-) 
next change from ToString() to ToString(CultureInfo.InvariantCulture) was needed ...

.. see code bellow ...
------------------------------------------------------------------
private void AddHeaders(
            HttpRequestMessage httpRequestMessage,
            IAuthenticator authenticator,
            string signedSignature,
            double timeStamp)
        {
            httpRequestMessage.Headers.Add("User-Agent", "GDAXClient");
            httpRequestMessage.Headers.Add("CB-ACCESS-KEY", authenticator.ApiKey);
            httpRequestMessage.Headers.Add("CB-ACCESS-TIMESTAMP", timeStamp.ToString(CultureInfo.InvariantCulture));
            httpRequestMessage.Headers.Add("CB-ACCESS-SIGN", signedSignature);
            httpRequestMessage.Headers.Add("CB-ACCESS-PASSPHRASE", authenticator.Passphrase);
        }

**Comment by dougdellolio** [comment]
i have added the fix here: https://github.com/dougdellolio/gdax-csharp/pull/32 if you agree, I will release in the next version 😄 

thanks so much!

**Comment by moski0** [comment]
yes.. 
thanks very much :-)
