### ISSUE TITLE
GET /products/<product-id>/candles

### ISSUE THREAD

**Issue by bmyatt** [dougdellolio/gdax-csharp#39]
Is this possible? I can't seem to find it, and I can't find another way to get the history.

**Comment by dougdellolio** [comment]
i believe you're looking for the items in this PR https://github.com/dougdellolio/gdax-csharp/pull/22

will try and get this merged as soon as possible.

**Comment by bmyatt** [comment]
Thanks!

**Comment by dougdellolio** [comment]
this is now added in v1.0.7. thanks!

https://github.com/dougdellolio/gdax-csharp/releases/tag/v1.0.7
