### ISSUE TITLE
Please add support for Bitcoin Cash

### ISSUE THREAD

**Issue by Steve0212a** [dougdellolio/gdax-csharp#44]
It is missing from your ProductType enum...

**Comment by dougdellolio** [comment]
Hi,

This was added with v1.0.7 here : https://github.com/dougdellolio/gdax-csharp/blob/master/GDAXClient/Shared/ProductType.cs#L14

let me know if you were referring to something else

**Comment by Steve0212a** [comment]
sorry, I was still on 1.06 and nuget did not tell me there was an update..  found it...
