### ISSUE TITLE
what is "signature" for Authenticator?

### ISSUE THREAD

**Issue by dimsaz** [dougdellolio/gdax-csharp#45]
Documentation says: 

//create an authenticator with your apiKey, **signature** and passphrase
var authenticator = new Authenticator("<apiKey>", "<signature>", "<passphrase>");

GDAX web site have 
1. passphrase, like "vy****szp"
2. API key like "8131******6fc971e6"
3. and "API secret" which is long string with == in the end. 

What is  **signature** which should be passed as second parameter? 

thanks

**Comment by dougdellolio** [comment]
@dimsaz the secret is the same as the signature. so the string ending in ==.

feel free to open up a PR and make that more clear in the readme if you would like

**Comment by dimsaz** [comment]
Thank you!!!

Thanks,
Dmitri

От: Doug Dellolio
Отправлено: Sunday, January 7, 2018 в 9:41 PM
Кому: dougdellolio/gdax-csharp
Копия: dimsaz; Mention
Тема: Re: [dougdellolio/gdax-csharp] what is "signature" for Authenticator?(#45)

@dimsaz the secret is the same as the signature. so the string ending in ==.
feel free to open up a PR and make that more clear in the readme if you would like
