### ISSUE TITLE
Account.Id is not the same type as the parameter for other calls

### ISSUE THREAD

**Issue by Sergy93** [dougdellolio/gdax-csharp#53]
I've found that each instance of Account in AccountsService.GetAllAccountsAsync() has an Id of type "Guid", but the account methods like GetAccountHistoryAsync() expect an int for the Id instead of a Guid.

**Comment by dougdellolio** [comment]
yeah... its inconsistent as its `string` in some places and `guid` in others. I believe this is elsewhere too. Should come up with a standard way and stick to it.... im thinking using Guid.

**Comment by jonnii** [comment]
🌞 🏖 🍸 🌭
