### ISSUE TITLE
stop order

### ISSUE THREAD

**Issue by linpiero** [dougdellolio/gdax-csharp#58]
Hello,
is it possible to add the possibility of adding a stop order?
Thank you

**Comment by dougdellolio** [comment]
yes. I am planning to add this very soon. I will leave this issue open until its added.

thanks

**Comment by linpiero** [comment]
Thanks to you!!

**Comment by dougdellolio** [comment]
@linpiero added with version v1.0.11. closing

**Comment by linpiero** [comment]
THX!!!!!
