### ISSUE TITLE
GetTrades

### ISSUE THREAD

**Issue by kawonekrypto** [dougdellolio/gdax-csharp#59]
Hello,

first of all thanks for this library :)

Any reason on why the getTrade method has not been implemented?
https://docs.gdax.com/#get-trades

Thanks,
K.

**Comment by kawonekrypto** [comment]
I see, maybe that would break the logic of the API? For real time updates you will need to keep the pageID for further requests.

**Comment by dougdellolio** [comment]
@kawonekrypto Just haven’t gotten around to it yet. Paging is already supported in this library so it won’t be too bad to implement. If you find you want to contribute, feel free to give it a shot otherwise I will get to it soon :)

**Comment by kawonekrypto** [comment]
@dougdellolio Correct me if I am wrong, pagination has been implemented to make the requests on all pages up to be done.
For my needs, I modified the request to just get back the first to limit my requests on Gdax API. 

 // This is the same method than SendHttpRequestMessagePagedAsync<T> without the request for the potential other pages
        protected async Task<IList<IList<T>>> SendHttpRequestMessageFirstPageAsync<T>(
            HttpMethod httpMethod,
            IAuthenticator authenticator,
            string uri,
            string content = null)
        {
            var pagedList = new List<IList<T>>();

            var httpRequestMessage = content == null
                ? httpRequestMessageService.CreateHttpRequestMessage(httpMethod, authenticator, uri)
                : httpRequestMessageService.CreateHttpRequestMessage(httpMethod, authenticator, uri, content);

            var httpResponseMessage = await httpClient.SendASync(httpRequestMessage).ConfigureAwait(false);
            var contentBody = await httpClient.ReadAsStringAsync(httpResponseMessage).ConfigureAwait(false);

            var firstPage = JsonConvert.DeserializeObject<IList<T>>(contentBody);

            pagedList.Add(firstPage);

            //if (!httpResponseMessage.Headers.TryGetValues("cb-after", out var firstPageAfterCursorId))
            //{
            //    return pagedList;
            //}

            //var t = firstPageAfterCursorId.First();

            //var subsequentPages = await GetAllSubsequentPages<T>(authenticator, uri, firstPageAfterCursorId.First());

            //pagedList.AddRange(subsequentPages);

            return pagedList;
        }

**Comment by dougdellolio** [comment]
@kawonekrypto correct. it sends a request to receive all pages and adds them to a list. what you have there looks correct if you want to get just the first page.

**Comment by chrisw000** [comment]
Is the issue here also that the parameter numberOfPages doesn't do what it implies?

When
numberOfPages = 0 means get ALL the pages, fair enough
numberOfPages = 1, we get 2 pages back
numberOfPages = 2, we get 3 pages back

The logic is flawed in that numberOfPages is used GetAllSubsequentPages without taking into account the initial page in the list.

**Comment by dougdellolio** [comment]
@chrisw000 just want to make sure this is working as expected before I close this. are you okay with me closing?

**Comment by chrisw000** [comment]
Sure… I’d managed to get confused perhaps similar to the original poster….. then thought I’d put a page size of 1 in my code… but actually typed page size of 2…

 

Works as expected

**Comment by dougdellolio** [comment]
released with v1.0.12
