### ISSUE TITLE
Post only limit order

### ISSUE THREAD

**Issue by jerdnanam** [dougdellolio/gdax-csharp#60]
Hello,

function PlaceLimitOrderAsync has postOnly attribute, but actually it is not used inside function, also it is not a part of GDAXClient.Services.Orders.Models.Order class. So post only flag does not work. Can you please implement this flag?

Thank you.

**Comment by dougdellolio** [comment]
Yes, this needs to be fixed. Feel free to take a shot at this and open a pull request, otherwise I can pick it up when I get a chance 

thanks!

**Comment by yoboto** [comment]
ahh that might explain why some of my recent limit orders have went through as "market" orders and been charged a fee?

Anyway, just signed up here to say a big thanks for this awesome library dougdellolio, i lack any web development skills, or json etc and would not be able to link up with GDAX in my program without your library.

Thanks again!

**Comment by dougdellolio** [comment]
@yoboto yes. this is now fixed with v1.0.11. please open up another issue if the problem persists.

and thanks for the words!
