### ISSUE TITLE
GetAllOrdersAsync(limit) is not working in Sandbox environment

### ISSUE THREAD

**Issue by kawonekrypto** [dougdellolio/gdax-csharp#63]
Hello,

GetAllOrdersAsync(limit) is not working in Sandbox environment but is working in prod environment (500 internal server error). Hence I guess this is not a problem with this library but with GDax directly.

Has anyone experienced the same and maybe has found a workaround?

Thanks,
K.

**Comment by dougdellolio** [comment]
yes, unfortunately the sandbox is no longer supported. haven't found any workarounds.
