### ISSUE TITLE
Include Limit Parameters in PlaceStopOrderAsync

### ISSUE THREAD

**Issue by hondajones97** [dougdellolio/gdax-csharp#65]
First of all, BIG THUMBS UP!  This project is awesome!  I'm curious as to the current ability to create Limit Stop Loss and Limit Stop Entry Orders.  Best I can tell Gdax recently(relatively) added documentation for their API concerning these.

Thanks!

**Comment by dougdellolio** [comment]
Thanks! I have not added these currently but would like to have them added soon. If you would like to try contributing, feel free to open a pull request with these changes. If not - leave this issue open and I will get to them shortly :)
