### ISSUE TITLE
JSON attributes on Models

### ISSUE THREAD

**Issue by chrisw000** [dougdellolio/gdax-csharp#70]
**Naming Conventions**
Quite a lot of the models have naming conventions like: Base_min_size which is at odds with standard .NET naming conventions... preferable to use attributes like [JsonProperty("Base_min_size")] in order to keep .NET naming conventions and allow the JSON serialization to work correctly?

**Strong Typing**
Some properties are left as String, when they could be stronger typed.
EG GDAXClient.Services.Fills.Models.Responses.FillResponse

Has a string property Product_id which elsewhere is typed as Enum GDAXClient.Shared.ProductType  (which incidentally should be called ProductId itself...)

This could be corrected by decorating the Enum and providing the correct JsonConverter attributes in the model.

Obviously these types of changes will break existing code, so would have an impact. 

The advantage being that the models will be self aware for serialize/deserialize - therefore removing any service specific code from the service methods... thus allowing the service method code to be future consolidated / improved to include things like Logging, Error Handling etc. while removing the repetitive code.

Happy to do the changes....

**Comment by dougdellolio** [comment]
yes... I have been meaning to do this but haven't gotten around to it. this would be great 😃

**Comment by chrisw000** [comment]
ok - I'll branch off from the work for #76 - so it will be done ontop of that change.

There is going to be quite a few changes - do you have any preference for how you'd prefer to look at them / merge them in?

**Comment by chrisw000** [comment]
RE "There is going to be quite a few changes - do you have any preference for how you'd prefer to look at them / merge them in?"

It's not taken very long.... so I've just done everything.... does mean there is quite a bit to review...

As I've only recently looked to use this project I don't have much code that makes use of it; therefore testing/running it has mostly relied on the test coverage.

That said - the changes are pretty trivial and the tests cover a great deal of the serialization side of things - so it should stand up quite well on first attempt.

Obviously the change requires renaming and stronger typing quite alot of properties - so the biggest challenge for someone updating to this version will be going through and re-wiring up the differences - EG there are now more Enums etc.

Also be aware - I've change quite a few property names from "Type" to something more specific so there are not lots of Enums called Type - and especially avoiding this due to Type being a Type of Type! :)

**Comment by dougdellolio** [comment]
thanks for your time on this @chrisw000. I left a comment on your PR. i hope it doesn't cause any extra work on your end. willing to work with you to get this in.
