### ISSUE TITLE
Namespace is same as classname for GDAXClient

### ISSUE THREAD

**Issue by chrisw000** [dougdellolio/gdax-csharp#71]
Namespace is GDAXClient

Main entry class into the API is also called GDAXClient

Meaning we get usage of GDAXClient.GDAXClient

This seems to cause [ReSharper](https://www.jetbrains.com/resharper/) big problems when creating (or opening for first time) a project that references GDAXClient; resulting in endless solution error noise as the compiler blows up.

[The Framework Design Guidelines say in section 3.4 "do not use the same name for a namespace and a type in that namespace"](https://stackoverflow.com/questions/18731415/namespace-and-class-with-the-same-name)

I know! This is the 2nd major breaking change request I've logged today regarding naming conventions :) I appreciate you'll have a reluctance to want to change something like this as its such high impact to existing users, for seemingly low gain.

But if the code can source send the compiler into a meltdown.... it will need to change one day if its ever to be more widely used..... 

I'd suggest a namespace of something like:
GdaxExchange.GdaxClient 

and leave the project / solution / folders etc. as they are?

Or just close this as Meh....

**Comment by confessore** [comment]
I noticed this as well but dismissed it as being insignificant.
maybe GDAXSharp.GDAXClient
as this is similar to the repository name ‘gdax-csharp’ while maintaining the same class name.

**Comment by confessore** [comment]
I’m still waiting on feedback for the pull request I made concerning a migration to dotnetcore2.0 as well as a fix for the PlaceLimitOrderAsync() method. I’ll probably make this namespace change in my fork just because it really is a good idea to keep namespaces and classes uniquely named

**Comment by chrisw000** [comment]
Yeah - on the one hand it is totally insignificant and changing it is a pain for anyone using the code....

But on the other hand - when the compiler blows its a nightmare working out what the problem really is.

**Comment by dougdellolio** [comment]
agreed we should fix this at some point and am open to PRs with this 👍 either name suggestion also works for me.

**Comment by dougdellolio** [comment]
thanks again @chrisw000 and @confessore for your work around this. going to close this now
