### ISSUE TITLE
WithdrawCrypto - Guid parsing fails

### ISSUE THREAD

**Issue by Heraisu** [dougdellolio/gdax-csharp#72]
Using the NuGet build latest as of 3/3/2018 -  version 1.0.11
Responses from WithdrawlsService.WithdrawToCryptoAsync(*) come back with an InnerException where the Id component fails to parse as a GUID. I am unable to process any Crypto withdraws.  Is there any way I can see the entire response string using the existing lib?

**Comment by Heraisu** [comment]
I see now that it's the INPUT parsing guid that's throwing the exception, not the response...
If that's so, that means the three parameters are a Currency type (eg BTC), a GUID for your own account, and an amount...  how are you supposed to give the address the withdraw is supposed to go to??

**Comment by Heraisu** [comment]
Found the issue
:
WithdrawService.cs:68   crypto_address = new Guid(crypto_address)
Crypto.cs:11          public Guid crypto_address { get; set; }

A crypto address should not be attempted to be converted as a Guid; and the corresponding datatype should not be attempting to store it as a Guid. It should be a string, clearly.
From what I can tell, there is no way that a Crypto withdraw would work under any circumstances with the current code.

**Comment by Heraisu** [comment]
I have confirmed that changing those lines to:
WithdrawService.cs:68 crypto_address = (crypto_address)
Crypto.cs:11 public string crypto_address { get; set; }

Resolved the issue and finally made the withdraw work correctly.

**Comment by dougdellolio** [comment]
@Heraisu I have created the fix for this here. https://github.com/dougdellolio/gdax-csharp/pull/74. If you agree with these changes I will merge and include in next release. 

thanks!
