### ISSUE TITLE
When requesting Historical Prices, dates are jumbled up

### ISSUE THREAD

**Issue by andyb1979** [dougdellolio/gdax-csharp#86]
I wanna get you a good + accurate bug report here but I'm seeing something wierd in ProductsService.GetHistoricalData. 

Here is my code:

```
// Actual from-to is 
// 5th March 03/05/2018 13:04:12 to 
// 12th March 03/12/2018 13:04:12 
var fromDate = DateTime.UtcNow.Subtract(TimeSpan.FromDays(7));
var toDate = DateTime.UtcNow;
ProductsService.GetHistoricRatesAsync(ProductType.BchBtc, fromDate, toDate, CandleGranularity.Hour1)
```

The response back from GDAX I debugged with Fiddler. The first bar contains Epoch 1520856000 and the last bar Epoch 1519783200. 

Using the (Epoch to Time converter here](https://www.unixtimestamp.com/index.php) these translate to 
from=02/28/2018 @ 2:00am (UTC)
to=03/12/2018 @ 12:00pm (UTC)

I'm not sure if GDAX is returning wrong results or if GDAXSharp is sending wrong request, but the response Candles do not contain the requested date range,

**Comment by andyb1979** [comment]
I think you can ignore -- problem might be in my code ... investigating

**Comment by andyb1979** [comment]
Yes ... I can get some sort of reproduction now. Check this out. This is my code using only GDAXSharp from NuGet v1.0.12

```
var gdaxClient = new GDAXClient.GDAXClient(new Authenticator(apiKey, secretkey, passphrase));

            // Actual from-to is 
            // 5th March 03/05/2018 13:04:12 to 
            // 12th March 03/12/2018 13:04:12 
            var fromDate = DateTime.UtcNow.Subtract(TimeSpan.FromDays(7));
            var toDate = DateTime.UtcNow;
            var rates = gdaxClient.ProductsService.GetHistoricRatesAsync(ProductType.BchBtc, fromDate, toDate, CandleGranularity.Hour1).Result;

            Console.WriteLine("Prices requested from {0} to {1} for instrument {2}", fromDate, toDate, ProductType.BchBtc);
            Console.WriteLine("First price received: {0}", rates.First().Time);
            Console.WriteLine("Last price received: {0}", rates.Last().Time);

            Console.ReadKey();
```

Console output is 

```
Prices requested from 03/05/2018 13:38:20 to 03/12/2018 13:38:20 for instrument BchBtc
First price received: 03/12/2018 13:00:00
Last price received: 02/28/2018 02:00:00
```

Only seems to matter if the latest date is UTCNow. If you pass any historical date in the past then it seems to return the exact requested timerange.

**Comment by andyb1979** [comment]
I can workaround this on my side. Plus I dont know if its a GDAX problem or yours. Just wanted to let you know!

**Comment by chrisw000** [comment]
I think the data returned is correct.... maybe the understanding is off?

The candle data from GDAX is set around the timeframe of the granularity...  rather than the timeframe of your requested range.

EG:  24 hour candles always go from 00:00 to 23:59 UTC  ( even if you ask from 01:23 etc)
6 hour candles always go from 00:00  06:00  12:00  18:00
1 hour candles always from the top of the hour
etc.

The GDAX docs also say that you may (or maynot) get additional data before the date range you've asked for - I assume this could be related to them caching responses.

This all makes sense - GDAX aren't going to compile custom candle rollups per request / requested timeframe down to the second.

**Comment by dougdellolio** [comment]
@andyb1979 thanks for reporting. i think @chrisw000 is on the money. can't speak to the reasoning why but as chris stated the api says the response may contain data that may precede the declared start value.

**Comment by andyb1979** [comment]
Hi guys,

I did some testing and discovered that GDAX gives some spurious results

If the time is aligned to a bar, say you have hourly and you request 00:00 - 12:00 then you will receive 00:00 - 11:00 (rounds down the start, the end is exclusive) 

If the time is not aligned to a bar, both sides round down, e.g. request 00:01 - 12:01 and hourly, you will receive 00:00 - 12:00

If the end time is UTCNOW or slightly in the future (perhaps my local time is out by a few seconds) then you receive 300 bars no matter what range you request. 

To resolve this what I've done is put some filters locally in my software to do bar rounding before making requests, and ensuring that the range is included Inclusive. 

I've also added integration tests in my code in case GDAX changes its behaviour in the future. 

Thanks guys for investigating!

**Comment by chrisw000** [comment]
The time on the candle bars is the start of the candle... so in your examples:

"say you have hourly and you request 00:00 - 12:00 then you will receive 00:00 - 11:00"
- this seems correct to me, the 11:00 bar contains data upto 12:00 (your end time)

"request 00:01 - 12:01 and hourly, you will receive 00:00 - 12:00"
- this also seems correct - the first 00:00 bar contains data for the 00:01 start time, and the 12:00 bar contains data for the end time supplied

"If the end time is UTCNOW or slightly in the future then you receive 300 bars no matter what range you request."
-> I didn't get this behavior when I tried
```
            var start = DateTime.UtcNow.AddDays(-1);
            var end = DateTime.UtcNow;
            var granularity = CandleGranularity.Hour1;
```

.... but maybe this has to do with what appears to be GDAX caching results from previous calls into it's service -see the GDAX docs?
