### ISSUE TITLE
Get current Mid Market Price

### ISSUE THREAD

**Issue by MRK89TP** [dougdellolio/gdax-csharp#87]
Hi, How can i get the mid market price in real time?
I tried something like this:

List<Candle> a = (List<Candle>)await gdaxClient.ProductsService.GetHistoricRatesAsync(GDAXSharp.Shared.ProductType.BtcEur, DateTime.Now, DateTime.Now, CandleGranularity.Minutes1);
a.First().Close;

or like this:

ProductStats a = await gdaxClient.ProductsService.GetProductStatsAsync(GDAXSharp.Shared.ProductType.BtcEur);
a.Last;

adding last in the ProductStats Class.

Is very similar to Mid Market Price shown on GDAX website  but not the same.

It is possible get it with third decimal digit?

Edit.
Maybe i found solution doing the avarage between prices of first Ask and fist Bid.

Thanks.

**Comment by chrisw000** [comment]
Real time mid market price would have to come off the live order book... as thats live data (not historic)

So the service you'd want is ProductsService.GetProductOrderBookAsync - and you'd only need level one data... 

Mid Market Price is defined in Wikipedia as being:

>  In financial markets, the mid price is the price between the best price of the sellers of the stock or commodity offer price or ask price and the best price of the buyers of the stock or commodity bid price. It can simply be defined as the average of the current bid and ask prices being quoted. 

Therefore... this would be how to determine it:         

```
var bestOrderBook = client.ProductsService.GetProductOrderBookAsync(ProductType.BtcEur, ProductLevel.One);

var bestBid = bestOrderBook.Result.Bids.FirstOrDefault()?.Price;
var bestAsk = bestOrderBook.Result.Asks.FirstOrDefault()?.Price;
var midMarketPrice = (bestBid + bestAsk) / 2m;
```

**Comment by dougdellolio** [comment]
thanks @chrisw000! what you have there looks right to me.

I would be cautious of the "real time" aspect of it as the API suggests using the websocket feed for realtime data. this is in the works

**Comment by chrisw000** [comment]
For entire historical data -> no idea! Obviously the price at each exchange will be slightly different anyway.
