### ISSUE TITLE
targetting .NetStandard 

### ISSUE THREAD

**Issue by chrisw000** [dougdellolio/gdax-csharp#90]
Have you got any thoughts on this?

I gave converting the projects a go - it's not all plain sailing. There are currently issues around getting the tests to run within Visual Studio. The test runner requires a pre-release version of Mono.Cecil, the tests are not auto discovered on a build - but they are discovered/run when manually running "All Tests" from test explorer.

It's also possible to have a separate solution, which has separate .csproj files that target .NetStandard, and live alongside the current solution / project. The only issue with this is that the /obj folders between the 2 solutions are not compatible with each other... fixed by telling them to output into differing `BaseIntermediaryOutputPath ` folders and adding an ignore to git

The actual library of GDAXSharp works perfectly as is and can target NET461 and NETSTANDARD2.0

**Comment by dougdellolio** [comment]
I would like to port this to net standard for sure. I am no rush to do this as I need to fully understand what it means and the impact it will have. If someone is using this already in their project. What does it mean to them? What changes?

**Comment by chrisw000** [comment]
I made it multi target; net461 and .netstandard 2.0 - so for people using it today... no change at all.

There was an additional nuget dependency on System.Net.Http - you're currently using the version baked into net461 (this dependency exists because the release .netcore release of this that was supposed to version match net461 had [bugs / compatibility issues](https://github.com/dotnet/corefx/issues/9846) which got fixed in later versions of System.Net.Http)

I don't know how you go about making the nuget package - but for that I guess its pretty useful?

Might be useful for you to look at / use to make nuget output from, even if it's not checked into /master?

I've dropped the solution & 2x project files here: https://github.com/chrisw000/gdax-csharp/commit/3bdc40128a137b8efb3743d7a608ce721280bb65

**Comment by dougdellolio** [comment]
cool! i will have some time tomorrow to play around with this more. ill get back to you

**Comment by dougdellolio** [comment]
@chrisw000 what if you only targeted net standard and not net461?

**Comment by chrisw000** [comment]
The issue is the tests.... 

The tests *must* run as net461 - there is currently no netStandard Specification . VS Runner

Because the tests run as net461 - they are looking for the net461 DLL output.

Which is why I multi targetted it....

If we momentarily ignored the tests - then yeah.... the actual GDAXSharp project could just be netStandard

When multi targetting it outputs different sets of DLLs; 

EG: the checked in project outputs:
net46, net461, netcoreapp1.1, netstandard2.0

This makes sense, because the netstandard output contains a bunch of linux info etc. whereas the net461 output has dependencies on the regular framework dlls

**Comment by chrisw000** [comment]
I've updated https://github.com/chrisw000/gdax-csharp/tree/feature/netStandard

So you don't need to delete the obj folder now...

**Comment by tritao** [comment]
We'd also like to use this library on .NET Core, would be great to this upstream.

**Comment by chrisw000** [comment]
@doug - sorry... I've been totally inactive for a while, stuff has cropped up.

The only issue when I setup what I did previously was that the test project cannot reliably be converted to .Net Standard.

The problem is out of our hands in that the problem is due to a dll dependency required for the mocking / test / testrunners

I'll try and take a look and see if the project that supplies that dll has now released a version that is .Net Standard compatible.... last time I looked they'd been working on it some months, and they had alot of bugs to resolve.

The code itself worked fine as .netStandard (last time I checked was before the websocket work went in) - so I'll have a go at getting that into my branch and see what happens.

**Comment by chrisw000** [comment]
OK - so I've updated the branch to catch up with upstream/master. 

Also, the dependency that was in beta has now been released.... so that part it good.

The visual studio runner for mspec still only works with net46 - so it can't see the tests when just targeting netStandard....

But, when I check the branch in, travis runs, builds .netStandard2.0 and runs all the tests, which work.

So the remaining issue is the VS2017 test runner.

There is a command line mspec runner, but obviously thats not so easy to use.

Previously I had the tests target net461, and the gdax-sharp project target net461 and netStandard - which seemed to work but maybe confusing?

If anyone can workout how to get the tests to run within Visual Studio, then you're all set....

**Comment by chrisw000** [comment]
I've just been looking at the code for the vs test runner, there is a bunch of conditional compilation for .net core vs .net46, in the area of code where its looking for the tests - presumably some work is required here so it can find the tests for netStandard.

Given that the console runner can identify the tests, I suppose it would be possible to borrow from the console runner codebase and fix the vs test runner....

**Comment by chrisw000** [comment]
Hmmm.... it was 3am when I finished up last night.... looking at it today.... the console runner actually says:

Contexts: 0, Specifications: 0, Time: 0.21 seconds

back to the drawing board...

**Comment by jonnii** [comment]
@chrisw000 try the following package combo:

```
<PackageReference Include="Machine.Specifications" Version="0.12.0" />
<PackageReference Include="Machine.Specifications.Runner.VisualStudio" Version="2.5.1" />
<PackageReference Include="Machine.Specifications.Should" Version="0.11.0" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
```

Long term you'd want to have a single csproj (in the new format) which outputs net461 and netstandard (i'd do 2.0 because i'm lazy). The tests should target netcoreapp2.0 and net461 - you can do this by doing something like `<TargetFrameworks>net461;netcoreapp2.0</TargetFrameworks>` (note that it's plural).

**Comment by jonnii** [comment]
This also works with newer versions of the above packages, i'd probably target the latest test sdk, which I think is 15.7?

**Comment by chrisw000** [comment]
@jonnii - Excellent!

I was targeting these:
```
    <PackageReference Include="Machine.Specifications.Runner.VisualStudio" Version="2.6.1" />
    <PackageReference Include="Machine.Specifications.Should" Version="0.11.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="Mono.Cecil" Version="0.10.0" />
```

and netStandard2.0

The magic ingredient was changing the tests to target `netcoreapp2.0`

Tests are now appearing in Visual Studio..... many thanks.

**Comment by jonnii** [comment]
With the new csproj format transitive dependencies work properly, so you can remove the cecil reference and things should work fine. Try changing the TargetFrameworks to include net461 along with netcoreapp2.0 just to make sure.

**Comment by chrisw000** [comment]
I've currently got it working as:

* single csproj (in the new format) which outputs net461;netstandard1.3;netstandard2.0
* tests target net461;netcoreapp2.0

The net461 build references the shipped 461 framework version of System.Net.Http

The netStandard1.3 build references the nuget 4.3.3 version of System.Net.Http

(The netStandard2.0 automatically picks up 4.3.3 version of System.Net.Http)

@jonnii / @dougdellolio  - what are your thoughts on just targeting .netStandard1.3 ? This can be used by net461 projects ( but they'll need to add a reference to the nuget 4.3.3 version of System.Net.Http )

**Comment by chrisw000** [comment]
[Travis logs here](https://travis-ci.org/chrisw000/gdax-csharp/builds/378763504)

**travis tests on net461**
`mono packages/machine.specifications.runner.console/0.9.3/tools/mspec.exe ./GDAXSharp.Specs/bin/Release/net461/GDAXSharp.Specs.dll`

- this finds / runs and passes the tests in the net461 dll

**travis tests on netcoreapp2.0**
`mono packages/machine.specifications.runner.console/0.9.3/tools/mspec.exe ./GDAXSharp.Specs/bin/Release/netcoreapp2.0/GDAXSharp.Specs.dll`

gives:
Contexts: 0, Specifications: 0, Time: 0.29 seconds

_bangs head against wall_


So then, locally (after deleting bin and obj to ensure totally clean rebuild) I've successfully built *just* netStandard1.3 and run/passed all tests, in Visual Studio via netcoreapp2.0

I've then checked that .netStandard1.3 + tests of netcoreapp2.0 in - and [Travis again doesn't find any tests on netcoreapp2.0](https://travis-ci.org/chrisw000/gdax-csharp/builds/378786721)

I've never used Travis / Linux etc. before, so it's quite possible I've not got something right in the travis file. It's been a voyage of trial and error to get this far....

**The travis script looks like this at the moment**

```
language: csharp
dotnet: 2.0.0
dist: trusty

script:
  - msbuild /t:restore GDAXSharp.sln /p:RestorePackagesPath=packages/
  - msbuild /t:build GDAXSharp.sln /p:Configuration=Release
  - mono packages/machine.specifications.runner.console/0.9.3/tools/mspec-clr4.exe ./GDAXSharp.Specs/bin/Release/net461/GDAXSharp.Specs.dll
  - mono packages/machine.specifications.runner.console/0.9.3/tools/mspec-clr4.exe ./GDAXSharp.Specs/bin/Release/netcoreapp2.0/GDAXSharp.Specs.dll
```

**Comments on what/why it's changed**
`donet: 2.0.0` so the netStandard SDKs etc. are installed, so we can compile that
`-msbuild` because the original xbuild doesn't want to build netStandard. Also, on Travis, using `dotnet restore` / `dotnet build` doesn't work for mixed output projects (ie net461 + netStandard x)
`restore` - so I could put the package path (couldn't work out where packages end up by default)
`mono` - the original mono pathing to mspec doesn't work when not running xbuild - I guess because xbuild puts it there like that.... hence adding the path in the restore step. 

I'm currently trying to run mspec against both net461 and netcoreapp2.0 DLLs

**why doesn't netcoreapp2.0 find the tests??**
no idea!

**Comment by chrisw000** [comment]
and finally...
targeting GDAXSharp to netStandard1.3 (only)
tests to net461 (only)

tests work in Visual Studio
tests work on Travis

There is only netStandard1.3 output for GDAXSharp

This can be referenced just fine from a net461 project **but there is a dependency on System.Net.Http that needs to be manually added via NuGet --> for users of the source code**

......hence asking about targeting netStandard1.3 only

Travis build for that is [here](https://travis-ci.org/chrisw000/gdax-csharp/builds/378818981)

I'm proposing this setup for the PR, or I'm gonna need some more input on how to get the tests to work in VS and Travis for both net461 / netcoreapp2.0 - all at the same time

**Comment by jonnii** [comment]
> what are your thoughts on just targeting .netStandard1.3 ? This can be used by net461 projects ( but they'll need to add a reference to the nuget 4.3.3 version of System.Net.Http )

So the conventional wisdom is to target the lowest netstandard that you can get away with but in my experience this leads to headaches. For example, if you target `netstandard1.3` and reference this from net461 _using the old csproj file format_ (e.g. not dotnet cli) you'll bring in the netstandard meta package which will mean you'll reference each individual `System.*` package. The solution to this is to target `net461` in your package...

If you're going to do that then the question becomes which `netcore` versions do you want to support, either `1.1` or `2.0` in which case you'd target `netstandard1.6` or `netstandard2.0` as these are the baselines. At this point as far as I'm concerned there is no reason to _not_ upgrade to `netcoreapp2.0` if you are a `1.1` user (the last remaining reason was for AWS lambda functions but this is now supported) so targetting `netstandard2.0` makes sense.

This decision will obviate the need to mess around with `System.Net.Http` - this is going to cause you headaches long term (fyi the version you want is `4.3.2` not `4.3.3`).

```
mono packages/machine.specifications.runner.console/0.9.3/tools/mspec.exe ./GDAXSharp.Specs/bin/Release/netcoreapp2.0/GDAXSharp.Specs.dll
```

You need to update the build to be using `dotnet test`. Your build script should look something like:

```
dotnet build src --configuration Release
dotnet test ./src/your.tests --configuration Release (or debug if you prefer)
```

You can't use the console runners any more.

**Comment by dougdellolio** [comment]
@chrisw000 i appreciate your time on this. I wish I could offer some better answers to your questions 😢 would it be worth switching away from Travis and looking at another tool, possibly Appveyor? If Travis is giving you problems.

thx @jonnii for chiming in

**Comment by chrisw000** [comment]
Progress!

https://travis-ci.org/chrisw000/gdax-csharp/builds/378997801
is building net461 / netStandard2.0

*AND* I'm now running net461 and netcoreapp2.0 tests - with all tests passing for each DLL

Its still failing the build - but I know why....
