### ISSUE TITLE
GetHistoricRatesAsync returns Internal Server Error

### ISSUE THREAD

**Issue by mrpmorris** [dougdellolio/gdax-csharp#91]
static void Main(string[] args)
		{
			var authenticator = new Authenticator(
				apiKey: "<redacted>",
				unsignedSignature: "<redacted>", 
				passphrase: "<redacted>");
			var gdaxClient = new GDAXClient(authenticator, true);

			Task<IList<Candle>> getHistoricRatesTask = gdaxClient.ProductsService.GetHistoricRatesAsync(
				productPair: GDAXSharp.Shared.Types.ProductType.BtcUsd,
				start: DateTime.UtcNow.AddHours(-8),
				end: DateTime.UtcNow,
				granularity: CandleGranularity.Hour6);
			getHistoricRatesTask.Wait();
			var response = getHistoricRatesTask.Result;
			Console.WriteLine("Done");
			Console.ReadLine();
		}

Could someone please test if this is currently working for you?

**Comment by dougdellolio** [comment]
@mrpmorris have you tried testing on the live server and not on the sandbox? i was able to successfully run it.

**Comment by mrpmorris** [comment]
Yes, that works. I wonder if the sandbox has a newer API?

Could this library perhaps throw exceptions if it receives error codes from the HTTP?

**Comment by chrisw000** [comment]
It should throw an HttpRequestException for that call....

Internal Server Error hints at an HTTP 500 error being thrown by the GDAX Server? 

Have a look at the httpResponseMessage.StatusCode on the response coming back - or run something like Fiddler to view the network traffic to see whats happening.

I've read elsewhere that the GDAX Sandbox often just isn't working.... its probably that.

**Comment by dougdellolio** [comment]
yes the last I heard the sandbox is no longer supported so I wouldn't rely on it.

the internal server error is returned from GDAX which means there was a problem with their server.
