### ISSUE TITLE
Account missing/invalid field?

### ISSUE THREAD

**Issue by Sotam** [dougdellolio/gdax-csharp#94]
I'm quite new at using GDAX API, but I've found some fields in your files that I couldn't find in the GET /Accounts. And the field `profile_id` is missing in this project.

To be precise, these are the fields that I couldn't find/retrieve from the GET /accounts 
https://github.com/dougdellolio/gdax-csharp/blob/d8ec9065b1e09ddd74f55a4c607151cd51e0561b/GDAXSharp/Services/Accounts/Models/Account.cs#L21-L25

**Comment by dougdellolio** [comment]
@Sotam nice catch. it definitely is missing.... might be a new field.

i have added it in https://github.com/dougdellolio/gdax-csharp/pull/95. will merge if no objection

**Comment by chrisw000** [comment]
yeah - add missing fields - the JSON deserialization works with/without fields including errors typos etc.

can't go wrong....

**Comment by Sotam** [comment]
@dougdellolio awesome, still one question left, these fields:
https://github.com/dougdellolio/gdax-csharp/blob/d8ec9065b1e09ddd74f55a4c607151cd51e0561b/GDAXSharp/Services/Accounts/Models/Account.cs#L21-L25 are not in the retrieved JSON, are those fields still used?

@chrisw000 isn't it safer to add the `JsonProperty` like `[JsonProperty("profile_id")]` for the Profile Id field? If Newtonsoft is really that smart, then this line: https://github.com/dougdellolio/gdax-csharp/blob/d8ec9065b1e09ddd74f55a4c607151cd51e0561b/GDAXSharp/Services/Accounts/Models/Account.cs#L12 isn't needed either (according to some testing) :)

**Comment by chrisw000** [comment]
Re [JsonProperty("profile_id")] --> the serialiser is using some settings that allow it to know about snake case namings... so it can automatically work out the something called ProfileId is profile_id on the json.

**Comment by dougdellolio** [comment]
@Sotam those fields may not be used. if you can confirm feel free to open a PR with those changes
