### ISSUE TITLE
Invalid API Key when GetAllAccounts

### ISSUE THREAD

**Issue by MRK89TP** [dougdellolio/gdax-csharp#97]
Hi, I've generated the api key on gdax selecting all permission 
![image](https://user-images.githubusercontent.com/29425006/37738045-03dfa744-2d56-11e8-8526-ac23229750f0.png)
The call to GetAllAccountsAsync returns "Invalid API Key".
But (for example) call to GetProductOrderBookAsync forks fine.

I missing something? Thanks

**Comment by MRK89TP** [comment]
I'm in sandbox.

**Comment by dougdellolio** [comment]
great.

last I tried the sandbox should still work with this call. Just make sure the ordering of the parameters you are passing in are correct.
